version: '3.8'
services:
# Setup backend
    backend:
        #backend image name
        image: playground-web-backend:latest
        build:
            context: ./backend
            dockerfile: ./backend.Dockerfile
        ports: 
            - '9000:9000'
        volumes:
            - ./backend:/app
            - ./app/node_modules
        command: npm start  

    # Setup frontend
    frontend:
        image: playground-web-frontend:latest
        build:
            context: ./frontend
            dockerfile: ./frontend.Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - /frontend:/app
            - /app/node_modules
        command: npm start
